# -*- coding: utf-8 -*-
"""cnn_predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mgqM9naaiIPQSFeShtBR32-jE-HBCcM
"""

import numpy as np
import pandas as pd
import fastbook
from fastbook import *
import os,gc,pathlib
import fastai.losses
import fastai.layers
from sklearn.metrics import confusion_matrix
from fastai import *
from fastai.vision import *
from fastai.vision.models import *
import torchvision.models as models

learner=load_learner("/content/drive/MyDrive/Colab Notebooks/pretrained_model/cnn/btc4_final.pkl")

def is_true(x):
    if x[0]=='yes':
        return "Tumor detected."
    else:
        return "Tumor not detected."

img=PILImage.create(f"/content/drive/MyDrive/Colab Notebooks/BrainTumor/no/2 no.jpeg")

x=learner.predict(img)

print("Test Result:",is_true(x),"\nProbability:",x[2])